name: "Assign Reviewers"
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: "Adding Teams and Persons for review"
      uses: dixahq/autoassign-reviewers-action@v0.8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        teams: "reviewers"         # only works for GitHub Organisation/Teams
